backend:
  name: git-gateway
  branch: master
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string, pattern: ".{1,}"}